name: CD

on:
  push:
    branches: generator
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow write access to repo
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: make it
      - name: Checkout pages
        uses: actions/checkout@v3
        with:
          ref: master
          path: deploy_dir
          fetch-depth: 0
      - name: move files
        run: |
          cd deploy_dir/
          git rm -r * -q
          cd ../
          mv dist/* deploy_dir/
          cd deploy_dir/
          git add .
          cd ../
      - name: diff files
        run: |
          cd deploy_dir/
          git diff --staged
          cd ../
      - name: deploy
        run: |
          PHP_CS_FIXER_VERSION=$(cat download/version.json | jq .number -r)
          cd deploy_dir/
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git commit -m "bump to v${PHP_CS_FIXER_VERSION}"
          git push
