name: CI

on:
  pull_request:
    branches: generator ## TODO: drop me

permissions:
  contents: read

jobs:
  test-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: make it
      - name: Checkout pages
        uses: actions/checkout@v3
        with:
          ref: master
          path: deploy_dir
          fetch-depth: 0
      - name: move files
        run: |
          cd deploy_dir/
          git rm -r * -q
          cd ../
          mv dist/* deploy_dir/
          cd deploy_dir/
          git add .
          cd ../
      - name: diff files
        run: |
          cd deploy_dir/
          git diff --staged
          cd ../
